# Esploratory Analysis

Please complete your proposal following the outline below.

## Blockbuster Insights: Exploring the Data Behind Top-Grossing Films


### Authors
Clara Guyot & Rianna Joseph
cguyot@uw.edu, riannaj@uw.edu

### Date
Spring 2024

## Abstract

Our initiative examines the data of the highest-grossing films to uncover trends and characteristics that contribute to their financial success. Understanding these trends is critical for filmmakers and industry professionals seeking to make well-informed choices and improve their chances of producing successful films. By studying box office success, genres, release dates, and other indicators, we want to give useful insights that might inform future film production strategies.

## Keywords

3-5 keywords that summarize your project.
(e.g., "Keywords: human physiology; bicycle exercise; Gen Z; times-series data")

Movie Revenue Patterns,
Box Office Insights,
Film Profitability


## Proposal

1. Introduction  

> Briefly introduce your project.  Include 3-5 research questions. What motivates the questions? Why are they important? (at least 200 words)

Our project Blockbuster Insights: Exploring the Data Behind Top-Grossing Films seeks to analyze the complexities of the film industry through statistical analysis of the highest-grossing films. We aim to answer a few significant research inquiries with the goal to shed light on the components that influence box office success and give industry experts useful information. Some of our research questions include:

What are the genres of the top-grossing movies? How has their popularity grown overtime and what correlation does that have to its success?

- This inquiry is prompted by a desire to better identify audience preferences and trends, which may help influence strategic film production and marketing decisions. 

How do release dates impact the box office success of films across different genres?

- By understanding the relationship between release dates and box office revenue we can make better informed decisions about release strategies, avoiding crowded periods, and maximizing audience engagement.

What are the relationships between production expenditures and box office results, and how do they vary by genre? 

- This inquiry focuses on the financial component of filmmaking and seeks to identify patterns in its association between investment and profitability.

2. Related Work  

> Describe your topic and related work in this space. You must include 3 citations to related work (URLs to similar work, high quality articles from the popular press, research papers, etc. ) Please use a standard citation style of your choice. (at least 200 words)

Our study digs into the complexities of the film business, with a special emphasis on the elements that influence a movie's box office performance. We want to discover patterns and trends in top-grossing films using statistical analysis, which will give significant information for industry professionals. Understanding these dynamics enables filmmakers and studio executives to make more educated choices about production, marketing, and distribution strategies.

Several studies have looked at comparable topics, providing useful insights into the link between various elements and box office results. Smit (2013), for example, carried out an in-depth investigation of box office performance, looking at the influence of critical reviews, marketing spend, and star power on movie profits. Their findings emphasize the multidimensional nature of film success and the relevance of include several variables in prediction models.
In a related study, Chen and Dai. (2022) looked into the influence of social media in driving box office revenue. They showed that online buzz and user-generated material had an impact on moviegoer behavior by examining data from Twitter and other social networks. Their findings highlight the rising importance of digital marketing methods in the modern film industry. Gao et al. (2019) also investigated the influence of release scheduling on box office success and financial analysis, taking into account seasonality and the importance of time periods. They also address the financial metric of net profit and reception metric in the form of ratings. Their research emphasizes the necessity of strategic release planning and identifies possible chances to increase audience engagement and revenue creation.

By expanding on these current studies and doing our own study of top-grossing films, we want to provide fresh insights to the area of film industry research, giving actionable advice for stakeholders looking to maximize their market performance.

> Citations

Chen, Yinchang, and Zhe Dai. “Mining of Movie Box Office and Movie Review Topics Using Social Network Big Data.” Frontiers in Psychology, U.S. National Library of Medicine, 26 May 2022, www.ncbi.nlm.nih.gov/pmc/articles/PMC9178289/. 

Gao, Zheng, et al. “How to Make a Successful Movie: Factor Analysis from Both ...” Indiana University, 2019, http://patshih.luddy.indiana.edu/publications/Gao-MovieSuccess-iConf19.pdf. 

Scott, Griffin. “Determinants of Box Office Performance - Uni Scholarworks.” UNI ScholarWorks, 2019, http://scholarworks.uni.edu/cgi/viewcontent.cgi?article=1143&context=mtie. 

Smit, Eon. “(PDF) the Determinants of Box Office Performance in the Film Industry Revisited.” Research Gate, Sept. 2013, www.researchgate.net/publication/281730174_The_determinants_of_box_office_performance_in_the_film_industry_revisited. 

3. The Dataset

> Where did you find the data? Please include a link to the data source  
> Who collected the data?  
> How was the data collected or generated?  
> Why was the data collected?  
>How many observations (rows) are in your data?  
> How many features (columns) are in the data?  
> What, if any, ethical questions or questions of power do you need to consider when working with this data?  
> What are possible limitations or problems with this data?   (at least 200 words)

The data was found from Kaggle, a website containing datasets with the goal of data science education. The dataset *Top Grossing Movies Dataset* was created and uploaded to Kaggle by Akanksha Gupta. Gupta gathered the data by utilizing the internet and collecting the data from internet searches for each top-grossing movie. According to Gupta, the data was collected as an introduction to the world of data science, based on Gupta's interest in the field. The dataset contains 1000 rows and there are 8 columns. While ethics are not a large concern when discussing top-grossing movies, on the surface, the movie industry itself has many unethical power dynamics. the top-grossing movies are the only thing highlighted in this dataset, the top-grossing movies being the films produced with large budgets by large movie production companies. Large movie production companies dominate the film industry leaving little room for artists and companies without the same financial means. This data is limited due to these ethical problems, as most movies are excluded from this dataset. Additionally, the dataset is limited due to the manner in which the research was done to collect the data. There may be many top-grossing movies that have been missed in this compilation of data. 

4. Implications

> Assuming you answer your research questions, briefly describe the expected or possible implications for technologists, designers, and policymakers. (at least 150 words)

The answers to our research questions can shed light on the correlations between the aspects contributing to making a top-grossing movie. These aspects are financial and social. Knowing how the budget contributes to movie success as well as which genres are drawing the most public interest benefits the movie industry. There is a benefit to technologists, designers, and policymakers in having insight into what the population cares about and what interests them. Movies are usually a reflection of what the population wants to consume. Technologists would be better able to predict and calculate the success of a movie. Based on the answers to our research questions, technologists can target marketing strategies. Designers can benefit through similar means; knowing what the public likes can allow them to focus their work on what is predicted to be popular. Lastly, policymakers can benefit by being more in touch with the public through the means of film. 

5. Limitations & Challenges
> What challenges or limitations might you need to address with your project idea more broadly? Briefly discuss. (at least 150 words)

We may face problems with determining which aspect(s): (financial, release date, genre, etc.) contributed to the success of a movie more. While insight can be gained from the data as a whole, the challenge comes when attempting to decipher what makes a top-grossing movie. Additionally, the question of how famous actors also may play a role in the popularity of a movie, as this is a large draw for consumers when selecting a movie to watch.  Additionally, the dataset solely relies on the gross profit for each movie regardless of real reviews. While profit is an effective way to gauge popularity, it leaves room for discrepancy when it comes to what the population enjoys.  

Additionally, while many top-grossing movies are included, the data does not account for all top-grossing movies. This may cause inaccurate outcomes to our research questions.  According to the-numbers.com, a website that has also compiled data for the top-grossing movies, there are well over 10,000 top-grossing movies. This is a large increase from our dataset which contains 1,000 top-grossing movies. The dataset is not adjusted to demonstrate how inflation impacts the gross profits of a film despite the wide period of time the movies were premiered. This could greatly alter the results to our research questions involving profit in determining a movie's popularity. International box office profits are either not included, or not differentiated within the dataset. While this may not be a limitation, it is important to take note of this challenge when discussing how policymakers can benefit from the data. 

### Table

Include a table of aggregate information

Describe why you included the table and what information it reveals

### Chart 1

Include a chart

Describe why you chose this chart and what information it reveals

Here's an example of how to run an R script inside an RMarkdown file:

``````{r, echo = FALSE, code = readLines("chart1_example.R")}
```

### Chart 2

Include a chart

Describe why you chose this chart and what information it reveals

### Chart 3

Include a chart

Describe why you chose this chart and what information it reveals
